### ISSUE TITLE
[Bug][github] Github Issue Assignees should collect all of the assignees

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2441] opened 2022-07-07 08:12 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Github Issue Assignees can be set to multi-users. But now it just collects one of the assignees.

### What you expected to happen

Collect all of the assignees.

### How to reproduce

![image](https://user-images.githubusercontent.com/3294100/177724726-6ca502df-48e1-4cfb-b873-9176a8f8d837.png)
![image](https://user-images.githubusercontent.com/3294100/177724893-e6ed915c-df1c-4bb9-8d99-3b2df226fafb.png)
![image](https://user-images.githubusercontent.com/3294100/177724996-04bab243-a084-457b-b33f-c26b0e19e07e.png)
https://docs.github.com/en/rest/issues/issues#list-repository-issues

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment] 2022-07-08 11:59
Hi @likyh @keon94 , this is not a bug. Unlike many project management tools like Jira, TAPD and teambition, only GitHub issues can be assigned to multiple assignees at the same time. When designing the domain layer schema at the first place, I chose not to add a table for the N-to-N relation between issues and assignees for simplicity.
I know that might cause confusion, but how about reconsider the design after users giving us specific feature requests for multi-assignees?

I'll close it and feel free to reopen.

**Closed by Startrekzky** 2022-07-08 11:59 UTC
Labels: type/bug
