### ISSUE TITLE
Jira basic auth token (need documentation)

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#1307] opened 2022-03-07 05:48 UTC
## Describe the bug
For jira cloud, we combine username and api token to get token, but for jira server, we used username and password. Not sure if it's caused by configuration of jira.

## To Reproduce
1. Go to config-ui jira data source
2. Click on 'key icon', type username and api token, then test connection, see error
3. retype username and password, test succeeded

## Expected behavior
We should use same way to configure basic auth token

**Comment by klesh** [comment] 2022-05-12 07:44
This is reality, users can use user/pass for jira server, but for jira cloud, it requires user/token as the combination.
We should document it some where, where do u think it is suitable @Startrekzky @yumengwang03

**Comment by klesh** [comment] 2022-06-13 09:39
need design @yumengwang03

**Comment by yumengwang03** [comment] 2022-06-17 13:31
@tanninghan is working on the design, which will be ready around next Tuesday.

**Comment by e2corporation** [comment] 2022-06-17 17:17
This is a duplicate of another recently opened ticket (https://github.com/apache/incubator-devlake/issues/2188) regarding config-ui and jira tooltip and it will be addressed on my current feature branch with a simple tooltip hint on the field I don't think we need new design elements created for this. @klesh @yumengwang03 

We'll just need the Copy/Text to use for the message.

<img width="955" alt="Screen Shot 2022-06-17 at 1 13 00 PM" src="https://user-images.githubusercontent.com/1742233/174346858-2fdc70d0-fd85-4f6b-b5b7-1928828d5958.png">

**Comment by e2corporation** [comment] 2022-06-17 17:18
Duplicate of / Replaced by #2188 (Reproduce steps also not accuate). It looks like we are also not giving the user the option to use a token generator any more? We need a documentation link here to add that points to Token use.

**Comment by Startrekzky** [comment] 2022-06-20 14:35
Close it as it duplicates with #2188

**Closed by Startrekzky** 2022-06-20 14:35 UTC
Labels: type/feature-request
