### ISSUE TITLE
[Bug][backend] not return correct http code when migrations needed

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2978] opened 2022-09-06 12:57 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/188640616-66b76d8b-7f7e-421d-be85-d964982f0c62.png)
No toast or modal to tell me to run migration when it's needed.

It maybe because of no correct HTTP code when migrations needed

### What you expected to happen

tell me what happened.

### How to reproduce

1. update Devlake version
2. open config-ui

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment] 2022-09-06 21:31
Duplicate Of and Relates to #2940

**Closed** 2022-09-08 03:55 UTC
Labels: type/bug
