### ISSUE TITLE
[Bug][config-ui] Blueprint runs don't show subtasks

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3239] opened 2022-09-28 15:39 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Blueprint runs don't show subtasks, I have no idea about the progress. After an hour's running, the run failed, which was frustrating.

![image](https://user-images.githubusercontent.com/14050754/192822807-c472dac8-c6bb-4063-8a93-91664d1ae140.png)

### What you expected to happen

Something like this:
![image](https://user-images.githubusercontent.com/14050754/192822981-4b9ed749-a082-48be-83f9-ccd1fe1f56d9.png)

### How to reproduce

Visit [here](https://ui-my-svr02.demo.devlake.io/) or your own config-ui and create a blueprint

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment] 2022-09-28 15:53
@likyh Do you want to take this one?

**Comment by mappjzc** [comment] 2022-09-28 15:54
![image](https://user-images.githubusercontent.com/2921251/192826984-3c1065b8-7d22-4b11-905a-e00a5ffd4dc0.png)
It say gateway time out, when try to getting task?

**Comment by likyh** [comment] 2022-09-29 03:10
logs:
```
time="2022-07-26 10:35:28" level=info msg="endpoint DELETE /plugins/ae/connections/:connectionId github.com/apache/incubator-devlake/api.RegisterRouter.func1 5"
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8080
time="2022-07-26 10:35:29" level=info msg=" [db] /app/services/pipeline.go:215 Error 1053: Server shutdown in progress
[0.283ms] [rows:0] SELECT * FROM `_devlake_pipelines` WHERE status = 'TASK_CREATED' ORDER BY id ASC LIMIT 1"
[mysql] 2022/07/26 10:35:30 packets.go:123: closing bad idle connection: EOF
[mysql] 2022/07/26 10:35:30 connection.go:173: driver: bad connection
time="2022-07-26 10:35:30" level=info msg=" [db] /app/services/pipeline.go:215 dial tcp 10.43.18.27:3306: connect: connection refused
[0.804ms] [rows:0] SELECT * FROM `_devlake_pipelines` WHERE status = 'TASK_CREATED' ORDER BY id ASC LIMIT 1"
time="2022-07-26 10:35:31" level=info msg=" [db] /app/services/pipeline.go:215 dial tcp 10.43.18.27:3306: connect: connection refused
[0.585ms] [rows:0] SELECT * FROM `_devlake_pipelines` WHERE status = 'TASK_CREATED' ORDER BY id ASC LIMIT 1"
time="2022-07-26 10:35:32" level=info msg=" [db] /app/services/pipeline.go:215 dial tcp 10.43.18.27:3306: connect: connection refused
[0.616ms] [rows:0] SELECT * FROM `_devlake_pipelines` WHERE status = 'TASK_CREATED' ORDER BY id ASC LIMIT 1"

```

**Comment by klesh** [comment] 2022-09-29 09:17
This might be caused by the DEMO server itself, up to this point, no one can reproduce the phenomenon on their local machine.
Let's watch it for one more day, we will close the issue tomorrow afternoon if none of us can reproduce it in the period.

**Comment by mappjzc** [comment] 2022-09-29 09:38
![image](https://user-images.githubusercontent.com/2921251/192997319-8a845f32-5c0f-46d1-84d0-1db80ba04292.png)
![image](https://user-images.githubusercontent.com/2921251/192997415-a482e648-49f9-4325-842a-3de5b67f9b1f.png)
![image](https://user-images.githubusercontent.com/2921251/192997476-3a63eb0a-5654-4bff-8d8b-338c7305cdbc.png)
![image](https://user-images.githubusercontent.com/2921251/192997505-cfd25345-8758-4c90-9ab5-cb7e8830c565.png)

**Closed** 2022-09-29 10:41 UTC
Labels: type/bug, priority/high

**Comment by Startrekzky** [comment] 2022-09-30 09:45
Verified.
