### ISSUE TITLE
[Bug][config-ui] Config-ui using values configured in a jira connection as default values when creating a new github connection

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3241] opened 2022-09-28 16:08 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Config-ui using values configured in a jira connection as default values when creating a new GitHub connection. As a result, the token was invalid and I had to delete it and re-type again.

![TxfMr0PAKi](https://user-images.githubusercontent.com/14050754/192829011-0dbc56ef-a271-4837-a7f8-7053239684fc.jpg)

### What you expected to happen

Not using values configured in other data source connections as the default values when creating any new connection.

### How to reproduce

1. go to config-ui
2. create a jira connection and fill in the form
3. create a github connection, see default values

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment] 2022-09-28 17:50
@Startrekzky This is a weird bug, it appears certain browsers like Firefox are encoding the default value of the password when it's empty, almost like it's auto-filling the password field. This behavior is not happening on Safari.

**Comment by e2corporation** [comment] 2022-09-28 17:53
@Startrekzky In Firefox, if I disable the setting "autofill passwords" the problem goes away. There is `autoComplete='false'` set on password fields, but the Browsers Seems to be ignoring this.

<img width="777" alt="Screen Shot 2022-09-28 at 1 52 45 PM" src="https://user-images.githubusercontent.com/1742233/192854068-781a5baa-0a26-4f91-8109-bdd67c13cdfe.png">

**Comment by e2corporation** [comment] 2022-09-28 17:55
@likyh Can you take a look at this too? Browser automatically filling in login/password fields and ignoring autoComplete=false

**Comment by e2corporation** [comment] 2022-09-28 17:59
> @likyh Can you take a look at this too? Browser automatically filling in login/password fields and ignoring autoComplete=false

Nevermind, I've isolated the root cause and it can be adjusted with tweaking `autoComplete` Prop

**Comment by e2corporation** [comment] 2022-09-28 18:43
Will be resolved by PR #3247

**Comment by mintsweet** [comment] 2022-09-29 08:18
I think it should be firefox's problem, you can delete the username and password saved on this URL.

**Comment by Startrekzky** [comment] 2022-12-23 13:14
Can this bug be fixed or is it worth fixing? @mintsweet  If not, I'll close it.

**Comment by klesh** [comment] 2022-12-26 03:20
@Startrekzky I don't think it can be fixed or worth fixing. Closing it, feel free to re-open for further discussion

**Closed by klesh** 2022-12-26 03:20 UTC
Labels: type/bug, priority/low
