### ISSUE TITLE
[Refactor][config-ui] use correct var name 

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3364] opened 2022-10-11 12:04 UTC
## What and why to refactor
https://github.com/apache/incubator-devlake/blob/24804f67423a726d955003589cc93bb773db16b2/config-ui/src/hooks/useDataScopesManager.jsx#L750-L775

Actually, `boardTransformations` and `projectTransformations` is `JiraBoard` array and project array.

## Describe the solution you'd like
use correct var name such as `projects` `projectList` or other.

**Comment by likyh** [comment] 2022-10-11 12:04
I'll fix it in https://github.com/apache/incubator-devlake/issues/3328 's PR

**Comment by likyh** [comment] 2022-10-11 12:09
`...projectTransformations.reduce(initializeTransformations, {})`: that is why `[object Object]` key exists in transfomation.

**Comment by e2corporation** [comment] 2022-10-11 14:42
`[object Object]` is a result of the comment I made on the other ticket regarding use of `entityIdKey` inside an Effect. `projectTransformations` contains an invalid entry, this is why the reducer fails and ends up with Object.

The problem isn't a direct result of how this line is structured.

**Comment by likyh** [comment] 2022-10-11 15:13
It because this issue. projectTransformations is objects array. initializeTransformations use object as key.

**Comment by e2corporation** [comment] 2022-10-11 16:44
My point is though is that `projectTransformations` is intended to be a collection of Project Key IDs... _not_ Objects, an object is unintentionally being given to that set, and that's what's responsible for this behavior. This was only happening after the PR for Deployment Options was merged with the altered use of `entityIdKey`

**Comment by e2corporation** [comment] 2022-10-11 16:51
The list get spreaded then reduced....  (`...projectTransformations`) so the `[cV]` key is supposed to be a valid entry after that point.

**Comment by likyh** [comment] 2022-10-12 01:45
@e2corporation This copy is wrong and another copy is right. So here set [object Object] into transformation here and another set by right key.

**Closed** 2022-10-17 03:08 UTC
Labels: type/refactor
